Sign up form
AnyiGP/movies-app pull request #5
Opened 2023-04-19 03:44 UTC by AnyiGP

Hola Adrián! Te paso esta pr en la que resolví el formulario para agregar usuarios. Me fata limpiar el formulario una vez que envío la info a firebase. Sigo con formulario de login en otra rama. Espero tus comentarios, gracias!!

2023-05-01 12:13 UTC, adrianmdp requested changes

2023-05-01 12:13 UTC, adrianmdp commented on src/components/forms/sign-up-form/index.tsx
> +    serviceUsers
Ojo acá xq estas haciendo un getAll pero en el catch tenes un mje "Error al guardar...".
Necesitas hacer ese get en este formulario?

2023-05-01 12:13 UTC, adrianmdp commented on src/utils/axios.ts
> +api.post("/users.json");
Esto no va en este archivo.

2023-05-05 20:02 UTC, AnyiGP commented on src/components/forms/sign-up-form/index.tsx
> +    serviceUsers
no, porque ya lo estoy haciendo en el servicio de usuarios. Entonces lo borro.

2023-05-05 20:03 UTC, AnyiGP commented on src/utils/axios.ts
> +api.post("/users.json");
listo, lo borro

2023-05-08 02:40 UTC, merged